# Generated by Django 5.0.6 on 2024-06-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messangerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
